Milestone/v0.2.0 (#57)
* temporary update job run

* adding min size 1 criteria for necessary config type list

* default to light theme

* support for alternate title for "No" in confirmDialog component; simplified mockConfig service;  supported tags for share-person feature; refactored security settings;

* Bump the npm_and_yarn group across 1 directory with 3 updates

Bumps the npm_and_yarn group with 3 updates in the / directory: [axios](https://github.com/axios/axios), [@babel/helpers](https://github.com/babel/babel/tree/HEAD/packages/babel-helpers) and [@babel/runtime](https://github.com/babel/babel/tree/HEAD/packages/babel-runtime).


Updates `axios` from 1.7.9 to 1.8.3
- [Release notes](https://github.com/axios/axios/releases)
- [Changelog](https://github.com/axios/axios/blob/v1.x/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v1.7.9...v1.8.3)

Updates `@babel/helpers` from 7.26.0 to 7.26.10
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.26.10/packages/babel-helpers)

Updates `@babel/runtime` from 7.26.0 to 7.26.10
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.26.10/packages/babel-runtime)

---
updated-dependencies:
- dependency-name: axios
  dependency-type: direct:production
  dependency-group: npm_and_yarn
- dependency-name: "@babel/helpers"
  dependency-type: indirect
  dependency-group: npm_and_yarn
- dependency-name: "@babel/runtime"
  dependency-type: indirect
  dependency-group: npm_and_yarn
...

Signed-off-by: dependabot[bot] <support@github.com>

* filtering issues to exclude PR as issue

* corrected typo in labels

* refactored check regression issue step

* approve PR if all checks are good

* added token env for gh commands

* updated inverted search to handle space

* replaced job name instead of workflow name for inprogress condition check

* added fallback empty value to avoid grep error

* updated fail check condition

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/pr_review.yml b/.github/workflows/pr_review.yml
--- a/.github/workflows/pr_review.yml
+++ b/.github/workflows/pr_review.yml
@@ -20,13 +20,15 @@ concurrency:
   cancel-in-progress: true
 
 permissions:
-  contents: write
-  issues: write
+  contents: read
+  issues: read
 
 jobs:
   workflow_eligible:
     name: Workflow Run eligibility
     runs-on: ubuntu-latest
+    outputs:
+      is-runnable: ${{ steps.pr-open.outputs.is-open != 'true' && steps.source-branch.outputs.non-mileston-pattern != 'true' }}
     steps:
       - name: Display Github object
         run: |
@@ -39,23 +41,26 @@ jobs:
             console.log("Github config: ", github)
             console.log("Github Rest API config: ", github.rest)
             console.log("Github Rest Issues API:", github.rest.issues)
-      - name: PR Should be open
+      - id: pr-open
+        name: PR Should be open
         if: github.event.pull_request.state != 'open'
         run: |
           echo "state should be open, skipping"
-          exit 0
-      - name: PR source branch milestone
+          echo "is-open=true" >> $GITHUB_OUTPUT
+      - id: source-branch
+        name: PR source branch milestone
         if: ${{ !startsWith(github.event.pull_request.head.ref, 'ref/head/milestone/') }}
         run: |
           echo "source branch for PR should be milestone, skipping"
           echo "found other source branch, ${{ github.event.pull_request.head.ref }}"
-          exit 0
+          echo "non-milestone-pattern=true" >> $GITHUB_OUTPUT
 
   required_props:
     name: validate PR Issues
     runs-on: ubuntu-latest
     needs: 
         - workflow_eligible
+    if: needs.workflow_eligible.outputs.is-runnable == 'true'
     steps:
         - name: Dont have milestone
           if: github.event.pull_request.milestone == null
@@ -120,35 +125,110 @@ jobs:
         uses: actions/github-script@v7
         with:
           script: |
-            const listIssuesResponse = await github.rest.issues.listForRepo({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              state: 'all',
-              milestone: context.payload.pull_request.milestone.number,
-              labels: ["regression", "testplan"],
-            });
-            console.log("listIssuesResponse: ", listIssuesResponse);
-            if(listIssuesResponse.data.length === 0 ) {
-                core.setFailed(`Regression tesplan is not found for milestone ${context.payload.pull_request.milestone.title}. Make sure to execute regression testplan before merging.`);
-            }
-            const commentPromises = listIssuesResponse.data.map(async regressionTestplanIssue => {
-                if(regressionTestplanIssue.state === "open") {
-                    // if this runs after all issues closed step, we never get error. but in case of step execute order changes
-                    core.setFailed(`regression testplan issue [#${regressionTestplanIssue.number}] is not completed yet`);
-                    throw new Error(`regression testplan issue [#${regressionTestplanIssue.number}] is not completed yet`);
+            const getRegressionTestplanIssue = async (pageNo) => {
+                pageNo = pageNo || 1;
+                if(pageNo > 5) {
+                    return [];
                 }
+                console.log("pageNo: ", pageNo);
+                const listIssuesResponse = await github.rest.issues.listForRepo({
+                    owner: context.repo.owner,
+                    repo: context.repo.repo,
+                    state: "all",
+                    milestone: context.payload.pull_request.milestone.number,
+                    labels: ["regression", "test plan"],
+                    sort: "updated"
+                });
+                console.log("listIssuesResponse: ", listIssuesResponse);
+                const filteredIssues = listIssuesResponse.data.filter(iss=>iss.title.startsWith("[Testplan]: Regression Test Plan"));
+                if(filteredIssues.length > 0) {
+                    return filteredIssues;
+                }
+                return await getRegressionTestplanIssue(pageNo+1)
+            };
+            const listRegressionIssues = await getRegressionTestplanIssue();
+            if(listRegressionIssues.length === 0 ) {
+                core.setFailed(`Regression tesplan is not found for milestone ${context.payload.pull_request.milestone.title}. Make sure to execute regression testplan before merging.`);
+                throw new Error(`Regression tesplan is not found for milestone ${context.payload.pull_request.milestone.title}. Make sure to execute regression testplan before merging.`);
+            }
+            const openRegressionIssue = listRegressionIssues.find(iss=>iss.state==="open");
+            if(openRegressionIssue) {
+                // if this runs after all issues closed step, we never get error. but in case of step execute order changes
+                core.setFailed(`regression testplan issue [#${openRegressionIssue.number}] is not completed yet`);
+                throw new Error(`regression testplan issue [#${openRegressionIssue.number}] is not completed yet`);
+            }
+            const hasCompleteComment = async ind => {
+                ind = ind || 0;
+                if(ind===listRegressionIssues.length) {
+                    return false;
+                }
+                const regressionIssue = listRegressionIssues[ind];
                 const listCommentsResponse = await github.rest.issues.listComments({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
-                    issue_number: regressionTestplanIssue.number
+                    issue_number: regressionIssue.number
                 });
                 console.log("listCommentsResponse: ", listCommentsResponse);
-                return listCommentsResponse.data.find(comment=> comment.body.includes("There are no critical issues") && comment.body.includes("Status-All%20Good"));
-            });
-            const completedComments = await Promise.all(commentPromises);
-            const foundCompletedComment = completedComments.find(comment=>!!comment);
-            if(!foundCompletedComment) {
+                const foundCompleteComment=!!listCommentsResponse.data.find(comment=> comment.body.includes("There are no critical issues") && comment.body.includes("Status-All%20Good"));
+                if (foundCompleteComment) {
+                    return true;
+                }
+                return await hasCompleteComment(ind+1);
+            };
+            const isRegressionCompleted = await hasCompleteComment();
+            if(!isRegressionCompleted) {
                 core.setFailed("Regression issue is closed but all critical issues are not resolved.");
+                throw new Error("Regression issue is closed but all critical issues are not resolved.");
             }
-            console.log("foundCompletedComment: ", foundCompletedComment);
+
+  wait-and-approve:
+    name: Wait for PR Checks and approve
+    runs-on: ubuntu-latest
+    needs: 
+        - validate
+    permissions: 
+        checks: read
+        pull-requests: write
+        statuses: read
+        contents: read
+    steps:
+      - name: Wait for All Checks to Finish
+        env:
+            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            JOB_NAME: "Wait for PR Checks and approve"
+        run: |
+          echo "Waiting for all checks to complete..."
+          while true; do
+            # Fetch the status of checks excluding this workflow
+            PR_CHECKS_OUTPUT=$(gh pr checks ${{ github.event.pull_request.number }} --repo "${{ github.repository }}" | grep -v "$JOB_NAME")
+            echo "$PR_CHECKS_OUTPUT"
+            STATUS=$(echo "$PR_CHECKS_OUTPUT" | grep -oE "pending|in_progress" || echo "")
+            
+            # Exit loop if no checks are pending or in progress
+            if [ -z "$STATUS" ]; then
+              echo "All checks have finished."
+              break
+            else
+              echo "Checks are still running. Retrying in 30 seconds..."
+              sleep 30
+            fi
+          done
+
+      - name: Verify Success of Other Checks
+        env:
+            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Ensure no check has failed
+          RESULT=$(gh pr checks ${{ github.event.pull_request.number }} --repo ${{ github.repository }} | grep -i "fail" || echo "nofailed")
+          if [[ "$RESULT" != "nofailed" ]]; then
+            echo "Found some failures: $RESULT"
+            exit 1
+          fi
+
+      - name: Approve PR
+        env:
+            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo "Approving pull request..."
+          gh pr review ${{ github.event.pull_request.number }} --approve --repo ${{ github.repository }}
 
