troubleshooting output display only if flag is enable; updated prod release conditions; updated post deployment issue notes; refactored demo deploy workflow;

diff --git a/.github/workflows/ui-demo-deploy.yml b/.github/workflows/ui-demo-deploy.yml
--- a/.github/workflows/ui-demo-deploy.yml
+++ b/.github/workflows/ui-demo-deploy.yml
@@ -1,16 +1,13 @@
-# Deploy UI for demo
-
 name: Deploy Demo UI
 
 # list of trigger events https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
 on:
-  workflow_run:
-    workflows: ["UI Build"]
-    types: [completed]
-    branches:
-      - master
-  # manual trigger allowed only for milestone branches
   workflow_dispatch:
+    inputs:
+      milestone_version:
+        description: Enter milestone title
+        required: true
+        type: string
 
 # only 1 workflow can be allowed for repository.
 concurrency:
@@ -22,66 +19,113 @@ permissions:
   contents: write
   deployments: write
 
+env:
+  DISPLAY_TROUBLESHOOT_OUTPUT: false
+
 jobs:
-  # test_echo:
-  #   name: print context values
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - run: |
-  #         echo github context json values = $GITHUB_CONTEXT_JSON
-  #         echo vars context json = $VARS_JSON
-  #       env:
-  #         GITHUB_CONTEXT_JSON: ${{ toJSON(github) }}
-  #         VARS_JSON: ${{ toJSON(vars) }}
-  validate_run:
-    name: Validating Run condition
+  run_eligible:
+    name: Workflow Run Eligible
     runs-on: ubuntu-latest
     outputs:
-      wfdispatch_eligible: ${{ steps.wf_dispatch.outputs.milestone_dispatch_run }}
-      wfrun_eligible: ${{ steps.wf_run.outputs.master_run }}
-      wfdispatchrun_eligible: ${{ steps.wf_dispatch_run.outputs.deploy_run }}
-      wfdispatchrun2_eligible: ${{ steps.wf_dispatch_run2.outputs.deploy_run2 }}
+      branch-or-tag-name: ${{ steps.verify-milestone-input.outputs.branchOrTagName }}
     steps:
-      - run: |
-          echo milestone_dispatch_run=true
-          echo milestone_dispatch_run=true >> $GITHUB_OUTPUT
-        id: wf_dispatch
-        if: github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')
-      - run: |
-          echo master_run=true
-          echo master_run=true >> $GITHUB_OUTPUT
-        id: wf_run
-        if: github.event_name == 'workflow_run' && github.ref=='refs/heads/master'
-      - run: |
-          echo deploy_run=true
-          echo deploy_run=true >> $GITHUB_OUTPUT
-        id: wf_dispatch_run
-        if: (github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')) || (github.event_name == 'workflow_run' && github.ref=='refs/heads/master')
-      - run: |
-          echo MILESTONE_RUN=$MILESTONE_RUN
-          echo MASTER_RUN=$MASTER_RUN
-          if [ "$MILESTONE_RUN" = true ] || [ "$MASTER_RUN" = true ]; then
-            echo deploy_run2=true
-            echo deploy_run2=true >> $GITHUB_OUTPUT
-          else
-            echo deploy_run2=false
-            echo deploy_run2=false >> $GITHUB_OUTPUT
-          fi
-        id: wf_dispatch_run2
+      - name: verify Workflow Branch
         env:
-          MILESTONE_RUN: ${{ steps.wf_dispatch.outputs.milestone_dispatch_run }}
-          MASTER_RUN: ${{ steps.wf_run.outputs.master_run }}
+          EVENT_NAME: ${{ github.event_name }}
+          BRANCH_NAME: ${{ github.ref }}
+          IS_REPO_OWNER: ${{ github.actor == github.repository_owner }}
+          IS_TRIGGERING_ACTOR_SAME: ${{ github.actor == github.triggering_actor }}
+        run: |
+          if [ "$EVENT_NAME" != "workflow_dispatch" ]; then
+            echo "only manual trigger is supported"
+            exit 1
+          fi
+          if [ "$BRANCH_NAME" != "refs/heads/master" ]; then
+            echo "Workflow trigger from master is only supported"
+            exit 1
+          fi
+          if [ "$IS_REPO_OWNER" != "true" ]; then
+            echo "Workflow is not triggered by owner"
+            exit 1
+          fi
+          if [ "$IS_TRIGGERING_ACTOR_SAME" == "false" ]; then
+            echo "Workflow is not triggered by owner"
+            exit 1
+          fi
+      - name: verify milestone input
+        id: verify-milestone-input
+        uses: actions/github-script@v7
+        with:
+          script: |
+            try {
+              // get milestone
+              const listMilestonesResponse = await github.rest.issues.listMilestones({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                state: "all"
+              });
+              console.log("listMilestonesResponse=", listMilestonesResponse);
+              const matchedMilestone = listMilestonesResponse.data.find(mlst=>mlst.title===context.payload.inputs.milestone_version);
+              if(!matchedMilestone) {
+                throw Error(`The requested milestone[${context.payload.inputs.milestone_version}] is not found.`);
+              }
+              const matchingBranchOrTagName = "";
+              if(matchedMilestone.state === "open" ) {
+                // either master or milestone branch are supported
+                const listBranchesResponse = await github.rest.repos.listBranches({
+                  owner: context.repo.owner,
+                  repo: context.repo.repo
+                });
+                console.log("listBranchesResponse: ", listBranchesResponse);
+                const milestoneBranch = listBranchesResponse.data.find(branchResponse=>branchResponse.name === `milestone/${context.payload.inputs.milestone_version}`);
+                if(milestoneBranch) {
+                  matchingBranchOrTagName = milestoneBranch.name
+                } else {
+                  console.log("milestone branch is not found, hence defaulting to master branch for open milestone. This could be false positive.")
+                  matchingBranchOrTagName = "master"
+                }
+              } else {
+                // only tags are supported
+                const listTagsResponse = await github.rest.repos.listTags({
+                  owner: context.repo.owner,
+                  repo: context.repo.repo
+                });
+                console.log("listTagsResponse: ", listTagsResponse);
+                const releasedTag = listTagsResponse.data.find(tagResponse=>tagResponse.name === context.payload.inputs.milestone_version);
+                if(!releasedTag) {
+                  throw new Error("Released Tag is not found for closed milestone.");
+                }
+                matchingBranchOrTagName = releasedTag.name
+              }
+              const getContentResponse = await github.rest.repos.getContent({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                path: "package.json",
+                ref: matchingBranchOrTagName
+              });
+              console.log("getContentResponse=", getContentResponse);
+              // compare package.json against milestone version 
+              const packageJsonContent = Buffer.from(getContentResponse.data.content, 'base64').toString();
+              const packageJsonObj = JSON.parse(packageJsonContent);
+              if(`v${packageJsonObj.version}` !== context.payload.inputs.milestone_version) {
+                throw new Error(`The requested milestone version [${context.payload.inputs.milestone_version}] is not found in package.json [v${packageJsonObj.version}] in [${matchingBranchOrTagName}]`);
+              }
+              core.setOutput("branchOrTagName", matchingBranchOrTagName);
+            } catch(e) {
+              console.error("failed reason: ", error);
+              core.setFailed(error.message);
+            }
 
   build:
     name: Build
     runs-on: ubuntu-latest
     needs:
-      - validate_run
-    # if: github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')
-    if: ${{ needs.validate_run.outputs.wfdispatch_eligible == 'true' }}
+      - run_eligible
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.run_eligible.outputs.branch-or-tag-name }}
       - name: Setup Node Latest
         # https://github.com/actions/setup-node
         uses: actions/setup-node@v4
@@ -90,16 +134,20 @@ jobs:
           cache: "npm"
       - run: npm --version
       - run: npm ci
+      - run: cp src/demo/demo.ts src/demo/index.ts
       - run: npm run build
 
   unittest:
     name: Unit Tests
     runs-on: ubuntu-latest
     needs:
+      - run_eligible
       - build
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.run_eligible.outputs.branch-or-tag-name }}
       - name: Setup Node Latest
         # https://github.com/actions/setup-node
         uses: actions/setup-node@v4
@@ -108,21 +156,22 @@ jobs:
           cache: "npm"
       - run: npm --version
       - run: npm ci
-      - run: npm run test --coverage
+      - run: npm run test
 
   deploy_demo:
-    name: gh page build
+    name: Deploy demo
     runs-on: ubuntu-latest
     needs:
       - unittest
-      - validate_run
+      - build
+      - run_eligible
     # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
     environment: github-pages
-    # if: (github.event_name == 'workflow_dispatch' && startsWith(github.ref,'refs/heads/milestone/')) || (github.event_name == 'workflow_run' && github.ref=='refs/heads/master')
-    if: ${{ always() && needs.validate_run.outputs.wfdispatchrun_eligible == 'true' }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.run_eligible.outputs.branch-or-tag-name }}
       - name: Setup Node Latest
         # https://github.com/actions/setup-node
         uses: actions/setup-node@v4
@@ -139,7 +188,6 @@ jobs:
           REACT_APP_MINIMUM_SESSION_TIME: ${{ vars.GH_REACT_APP_MINIMUM_SESSION_TIME }}
           GENERATE_SOURCEMAP: ${{ vars.GH_GENERATE_SOURCEMAP }}
           PUBLIC_URL: ${{ vars.GH_PUBLIC_URL }}
-      # - run: gh-pages -d build
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v4
         with:
